name: CloudSystem
version: 2.0.0
author: "Nils", "SkyZoneMC"
api: 3.0.2
main: Sign\CloudSystem\CloudSystem
description: CloudSytem
commands: /cloud sign
  cloud:
    description: CloudSystem Command
    aliases: [cloudsystem]
