name: CloudSystem
version: 2.0.0
api: 3.0.2
main: Sign\CloudSystem\CloudSystem
author: "SkyZoneMC"
description: CloudSytem
commands:
        cloud:
             description: CloudSystem Command
             aliases: [cloudsystem]
