name: CloudSystem
version: 2.0.0
api: 3.0.2
main: Sign\CloudSystem\CloudSystem
author: ["Nils", "SkyZoneMC"]
description: CloudSytem
website: http://AtomicMC.tk
commands: /cloud sign
  cloud:
    description: CloudSystem Command
    aliases: [cloudsystem]
