name: CloudSystem
version: 2.0
api: [3.1.1]
main: Sign\CloudSystem\CloudSystem
description: CloudSystem
commands: /cloud sign
  cloud:
    description: CloudSystem Command
    aliases: [cloudsystem]
